CREATE TABLE sale_status
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_salestatus PRIMARY KEY (id)
);

INSERT INTO public.sale_status (id, name) VALUES (1, 'ACCEPTED');
INSERT INTO public.sale_status (id, name) VALUES (2, 'SENDET');
INSERT INTO public.sale_status (id, name) VALUES (3, 'REJECTED');
INSERT INTO public.sale_status (id, name) VALUES (4, 'DONE');
