CREATE TABLE sale_item
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         VARCHAR(255),
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(255),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    deleted_date       TIMESTAMP WITHOUT TIME ZONE,
    deleted_by         VARCHAR(255),
    deleted            BOOLEAN                                 NOT NULL,
    name               VARCHAR(255),
    product_id         BIGINT,
    schedule           TIMESTAMP WITHOUT TIME ZONE,
    comments           VARCHAR(255),
    number_nakladnoy   INTEGER,
    address            VARCHAR(255),
    quantity           INTEGER,
    client_id          BIGINT,
    sale_status        BIGINT,
    total_price        DOUBLE PRECISION,
    CONSTRAINT pk_saleitem PRIMARY KEY (id)
);

ALTER TABLE sale_item
    ADD CONSTRAINT FK_SALEITEM_ON_CLIENT FOREIGN KEY (client_id) REFERENCES client (id);

ALTER TABLE sale_item
    ADD CONSTRAINT FK_SALEITEM_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);

ALTER TABLE sale_item
    ADD CONSTRAINT FK_SALEITEM_ON_SALE_STATUS FOREIGN KEY (sale_status) REFERENCES sale_status (id);