CREATE TABLE filial
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         VARCHAR(255),
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(255),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    deleted_date       TIMESTAMP WITHOUT TIME ZONE,
    deleted_by         VARCHAR(255),
    deleted            BOOLEAN                                 NOT NULL,
    name               VARCHAR(255),
    fil_code           VARCHAR(255),
    storage_id         BIGINT,
    CONSTRAINT pk_filial PRIMARY KEY (id)
);

ALTER TABLE filial
    ADD CONSTRAINT uc_filial_storage UNIQUE (storage_id);

ALTER TABLE filial
    ADD CONSTRAINT FK_FILIAL_ON_STORAGE FOREIGN KEY (storage_id) REFERENCES storage (id);


INSERT INTO public.filial (id, created_by, created_date, deleted, deleted_by, deleted_date, last_modified_by, last_modified_date, fil_code, name, storage_id) VALUES (1, null, null, false, null, null, null, null, 'test', 'test', null);

