CREATE TABLE use
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         VARCHAR(255),
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(255),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    deleted_date       TIMESTAMP WITHOUT TIME ZONE,
    deleted_by         VARCHAR(255),
    deleted            BOOLEAN                                 NOT NULL,
    pin                VARCHAR(255)                            NOT NULL,
    surname            VARCHAR(255)                            NOT NULL,
    name               VARCHAR(255)                            NOT NULL,
    patronymic         VARCHAR(255),
    position           VARCHAR(255),
    phone              VARCHAR(255)                            NOT NULL,
    email              VARCHAR(255),
    password           VARCHAR(255)                            NOT NULL,
    is_active          BOOLEAN DEFAULT TRUE,
    address            VARCHAR(255),
    procent_skidki     INTEGER,
    type_client        BOOLEAN,
    CONSTRAINT pk_use PRIMARY KEY (id)
);

CREATE TABLE use_filials
(
    filial_id BIGINT NOT NULL,
    use_id    BIGINT NOT NULL
);

CREATE TABLE use_roles
(
    user_id  BIGINT NOT NULL,
    roles_id BIGINT NOT NULL
);

ALTER TABLE use
    ADD CONSTRAINT uc_use_pin UNIQUE (pin);

ALTER TABLE use_roles
    ADD CONSTRAINT fk_use_roles_on_role FOREIGN KEY (roles_id) REFERENCES role (id);

ALTER TABLE use_roles
    ADD CONSTRAINT fk_use_roles_on_user FOREIGN KEY (user_id) REFERENCES use (id);

ALTER TABLE use_filials
    ADD CONSTRAINT fk_usefil_on_filial FOREIGN KEY (filial_id) REFERENCES filial (id);

ALTER TABLE use_filials
    ADD CONSTRAINT fk_usefil_on_user FOREIGN KEY (use_id) REFERENCES use (id);

INSERT INTO public.use (id, created_by, created_date, deleted, deleted_by, deleted_date, last_modified_by, last_modified_date, address, email, is_active, name, password, patronymic, phone, pin, position, procent_skidki, surname, type_client) VALUES (1, 'admin', '2023-07-11 14:03:29.000000', false, null, null, null, null, 'test@mail.ru', 'true', true, 'wfqwfq', '$2a$12$Zpp44g2ozOmVsJiynrAe.uayARURRxBfqxGgKNJb5Kg86qWZXPw5G', 'test', 'admin', 'admin', 'test', null, 'vdev', null);
INSERT INTO public.use_filials (use_id, filial_id) VALUES (1, 1);
INSERT INTO public.use_roles (user_id, roles_id) VALUES (1, 1);
