CREATE TABLE orders
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         VARCHAR(255),
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(255),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    deleted_date       TIMESTAMP WITHOUT TIME ZONE,
    deleted_by         VARCHAR(255),
    deleted            BOOLEAN                                 NOT NULL,
    user_id            BIGINT,
    status             BIGINT,
    address            VARCHAR(255),
    phone_number       VARCHAR(255),
    date_delivery      TIMESTAMP WITHOUT TIME ZONE,
    name               VARCHAR(255),
    comment            VARCHAR(255),
    total_amount       DOUBLE PRECISION,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_STATUS FOREIGN KEY (status) REFERENCES sale_status (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_USER FOREIGN KEY (user_id) REFERENCES use (id);