CREATE TABLE storage_item
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    storage_id BIGINT,
    product_id UUID,
    quantity   INTEGER                                 NOT NULL,
    CONSTRAINT pk_storageitem PRIMARY KEY (id)
);

ALTER TABLE storage_item
    ADD CONSTRAINT FK_STORAGEITEM_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);

ALTER TABLE storage_item
    ADD CONSTRAINT FK_STORAGEITEM_ON_STORAGE FOREIGN KEY (storage_id) REFERENCES storage (id);