CREATE TABLE sale_item
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         VARCHAR(255),
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(255),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    deleted_date       TIMESTAMP WITHOUT TIME ZONE,
    deleted_by         VARCHAR(255),
    deleted            BOOLEAN                                 NOT NULL,
    name               VARCHAR(255),
    schedule           TIMESTAMP WITHOUT TIME ZONE,
    comments           VARCHAR(255),
    number_nakladnoy   VARCHAR(255),
    address            VARCHAR(255),
    phone_number       VARCHAR(255),
    quantity           INTEGER,
    client_id          BIGINT,
    sale_status        BIGINT,
    total_price        DOUBLE PRECISION,
    CONSTRAINT pk_saleitem PRIMARY KEY (id)
);

CREATE TABLE sale_item_product
(
    product_id   UUID NOT NULL,
    sale_item_id BIGINT NOT NULL
);

ALTER TABLE sale_item
    ADD CONSTRAINT FK_SALEITEM_ON_CLIENT FOREIGN KEY (client_id) REFERENCES client (id);

ALTER TABLE sale_item
    ADD CONSTRAINT FK_SALEITEM_ON_SALE_STATUS FOREIGN KEY (sale_status) REFERENCES sale_status (id);

ALTER TABLE sale_item_product
    ADD CONSTRAINT fk_salitepro_on_product FOREIGN KEY (product_id) REFERENCES product (id);

ALTER TABLE sale_item_product
    ADD CONSTRAINT fk_salitepro_on_sale_item FOREIGN KEY (sale_item_id) REFERENCES sale_item (id);