ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS description TEXT,
    ADD COLUMN IF NOT EXISTS number_nakladnoy TEXT,
    ADD COLUMN IF NOT EXISTS schedule TIMESTAMP WITHOUT TIME ZONE,
    ADD COLUMN IF NOT EXISTS client_id BIGINT;

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_CLIENT FOREIGN KEY (client_id) REFERENCES client (id);
