CREATE TABLE transfer
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         VARCHAR(255),
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(255),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    deleted_date       TIMESTAMP WITHOUT TIME ZONE,
    deleted_by         VARCHAR(255),
    deleted            BOOLEAN                                 NOT NULL,
    transfer_date      TIMESTAMP WITHOUT TIME ZONE,
    from_storage_id    BIGINT,
    to_filial_id       BIGINT,
    CONSTRAINT pk_transfer PRIMARY KEY (id)
);

ALTER TABLE transfer
    ADD CONSTRAINT FK_TRANSFER_ON_FROM_STORAGE FOREIGN KEY (from_storage_id) REFERENCES storage (id);

ALTER TABLE transfer
    ADD CONSTRAINT FK_TRANSFER_ON_TO_FILIAL FOREIGN KEY (to_filial_id) REFERENCES filial (id);


CREATE TABLE transfer_item
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id  UUID,
    quantity    INTEGER                                 NOT NULL,
    transfer_id BIGINT,
    CONSTRAINT pk_transferitem PRIMARY KEY (id)
);

ALTER TABLE transfer_item
    ADD CONSTRAINT FK_TRANSFERITEM_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);

ALTER TABLE transfer_item
    ADD CONSTRAINT FK_TRANSFERITEM_ON_TRANSFER FOREIGN KEY (transfer_id) REFERENCES transfer (id);