CREATE TABLE supplier
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         VARCHAR(255),
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(255),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    deleted_date       TIMESTAMP WITHOUT TIME ZONE,
    deleted_by         VARCHAR(255),
    deleted            BOOLEAN                                 NOT NULL,
    name               VARCHAR(255),
    surname            VARCHAR(255),
    patronymic         VARCHAR(255),
    phone_number       VARCHAR(255),
    email              VARCHAR(255),
    password           VARCHAR(255),
    pin                VARCHAR(255),
    is_active          BOOLEAN,
    role_id            BIGINT,
    CONSTRAINT pk_supplier PRIMARY KEY (id)
);

ALTER TABLE supplier
    ADD CONSTRAINT FK_SUPPLIER_ON_ROLE FOREIGN KEY (role_id) REFERENCES role (id);