CREATE TABLE wish_list_filial
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         VARCHAR(255),
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(255),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    deleted_date       TIMESTAMP WITHOUT TIME ZONE,
    deleted_by         VARCHAR(255),
    deleted            BOOLEAN                                 NOT NULL,
    is_served          BOOLEAN,
    filial_id          BIGINT,
    CONSTRAINT pk_wishlistfilial PRIMARY KEY (id)
);

ALTER TABLE wish_list_filial
    ADD CONSTRAINT FK_WISHLISTFILIAL_ON_FILIAL FOREIGN KEY (filial_id) REFERENCES filial (id);


CREATE TABLE wish_list_item_filial
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id          UUID,
    wish_list_filial_id BIGINT,
    quantity            INTEGER,
    CONSTRAINT pk_wishlistitemfilial PRIMARY KEY (id)
);

ALTER TABLE wish_list_item_filial
    ADD CONSTRAINT FK_WISHLISTITEMFILIAL_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);

ALTER TABLE wish_list_item_filial
    ADD CONSTRAINT FK_WISHLISTITEMFILIAL_ON_WISHLISTFILIAL FOREIGN KEY (wish_list_filial_id) REFERENCES wish_list_filial (id);