CREATE TABLE return_filial
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         VARCHAR(255),
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(255),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    deleted_date       TIMESTAMP WITHOUT TIME ZONE,
    deleted_by         VARCHAR(255),
    deleted            BOOLEAN                                 NOT NULL,
    from_filial_id     BIGINT,
    to_storage_id      BIGINT,
    status             VARCHAR(255),
    return_date        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_returnfilial PRIMARY KEY (id)
);

ALTER TABLE return_filial
    ADD CONSTRAINT FK_RETURNFILIAL_ON_FROM_FILIAL FOREIGN KEY (from_filial_id) REFERENCES filial (id);

ALTER TABLE return_filial
    ADD CONSTRAINT FK_RETURNFILIAL_ON_TO_STORAGE FOREIGN KEY (to_storage_id) REFERENCES storage (id);


CREATE TABLE return_filial_item
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id UUID,
    quantity   INTEGER                                 NOT NULL,
    return_id  BIGINT,
    CONSTRAINT pk_returnfilialitem PRIMARY KEY (id)
);

ALTER TABLE return_filial_item
    ADD CONSTRAINT FK_RETURNFILIALITEM_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);

ALTER TABLE return_filial_item
    ADD CONSTRAINT FK_RETURNFILIALITEM_ON_RETURN FOREIGN KEY (return_id) REFERENCES return_filial (id);