CREATE TABLE storage
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255),
    storage_code VARCHAR(255),
    address      VARCHAR(255),
    CONSTRAINT pk_storage PRIMARY KEY (id)
);