CREATE TABLE supply
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         VARCHAR(255),
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(255),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    deleted_date       TIMESTAMP WITHOUT TIME ZONE,
    deleted_by         VARCHAR(255),
    deleted            BOOLEAN                                 NOT NULL,
    name               VARCHAR(255),
    storage_id         BIGINT,
    CONSTRAINT pk_supply PRIMARY KEY (id)
);

ALTER TABLE supply
    ADD CONSTRAINT FK_SUPPLY_ON_STORAGE FOREIGN KEY (storage_id) REFERENCES storage (id);