CREATE TABLE discount_category
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    percentage DOUBLE PRECISION,
    CONSTRAINT pk_discountcategory PRIMARY KEY (id)
);

INSERT INTO public.discount_category (id, name, percentage) VALUES (1, 'bronze', 5);
INSERT INTO public.discount_category (id, name, percentage) VALUES (2, 'silver', 10);
INSERT INTO public.discount_category (id, name, percentage) VALUES (3, 'gold', 15);
INSERT INTO public.discount_category (id, name, percentage) VALUES (4, 'no discount', 0);
