CREATE TABLE discount_category
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    percentage DOUBLE PRECISION,
    CONSTRAINT pk_discountcategory PRIMARY KEY (id)
);