CREATE TABLE client
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                 VARCHAR(255),
    surname              VARCHAR(255),
    patronymic           VARCHAR(255),
    phone_number         VARCHAR(255),
    discount_category_id BIGINT,
    client_type_id       BIGINT,
    CONSTRAINT pk_client PRIMARY KEY (id)
);

ALTER TABLE client
    ADD CONSTRAINT FK_CLIENT_ON_CLIENT_TYPE FOREIGN KEY (client_type_id) REFERENCES client_type (id);

ALTER TABLE client
    ADD CONSTRAINT FK_CLIENT_ON_DISCOUNT_CATEGORY FOREIGN KEY (discount_category_id) REFERENCES discount_category (id);